modLoader = "kotlinforforge"
loaderVersion = "${forgelike_adapter_version_range}"
issueTrackerURL = "https://github.com/ejektaflex/Percale/issues"
license = "MPL 2.0"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
logoFile="assets/${mod_id}/icon.png"
authors = "${mod_author}"
description = '''
${description}
'''
#logoFile = ""

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "kotlinforforge"
type = "required"
versionRange = "${forgelike_adapter_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
